// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PUP_Online_Lagoon_System.Models;

#nullable disable

namespace PUP_Online_Lagoon_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260116010703_MoreNullDependencies")]
    partial class MoreNullDependencies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PUP_Online_Lagoon_System.Models.Account.Customer", b =>
                {
                    b.Property<string>("Customer_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContactNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Customer_ID");

                    b.HasIndex("User_ID")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("PUP_Online_Lagoon_System.Models.Account.User", b =>
                {
                    b.Property<string>("User_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PUP_Online_Lagoon_System.Models.Account.Vendor", b =>
                {
                    b.Property<string>("Vendor_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContactNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stall_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("User_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Vendor_ID");

                    b.HasIndex("Stall_ID");

                    b.HasIndex("User_ID")
                        .IsUnique();

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("PUP_Online_Lagoon_System.Models.Orders.ItemOrder", b =>
                {
                    b.Property<string>("Order_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Customer_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EstPickupTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("float");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stall_ID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Order_ID");

                    b.HasIndex("Customer_ID");

                    b.HasIndex("Stall_ID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PUP_Online_Lagoon_System.Models.Orders.OrderDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Food_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Order_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("OriginalPrice")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("Subtotal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Food_ID");

                    b.HasIndex("Order_ID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("PUP_Online_Lagoon_System.Models.Stall.FoodItem", b =>
                {
                    b.Property<string>("Food_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("FoodDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Stall_ID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Food_ID");

                    b.HasIndex("Stall_ID");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("PUP_Online_Lagoon_System.Models.Stall.FoodStall", b =>
                {
                    b.Property<string>("Stall_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PrepTime")
                        .HasColumnType("int");

                    b.Property<string>("StallDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StallName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Vendor_ID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Stall_ID");

                    b.HasIndex("Vendor_ID");

                    b.ToTable("FoodStalls");
                });

            modelBuilder.Entity("PUP_Online_Lagoon_System.Models.Account.Customer", b =>
                {
                    b.HasOne("PUP_Online_Lagoon_System.Models.Account.User", "User")
                        .WithOne()
                        .HasForeignKey("PUP_Online_Lagoon_System.Models.Account.Customer", "User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PUP_Online_Lagoon_System.Models.Account.Vendor", b =>
                {
                    b.HasOne("PUP_Online_Lagoon_System.Models.Stall.FoodStall", "Stall")
                        .WithMany()
                        .HasForeignKey("Stall_ID");

                    b.HasOne("PUP_Online_Lagoon_System.Models.Account.User", "User")
                        .WithOne()
                        .HasForeignKey("PUP_Online_Lagoon_System.Models.Account.Vendor", "User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stall");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PUP_Online_Lagoon_System.Models.Orders.ItemOrder", b =>
                {
                    b.HasOne("PUP_Online_Lagoon_System.Models.Account.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("Customer_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PUP_Online_Lagoon_System.Models.Stall.FoodStall", "Stall")
                        .WithMany()
                        .HasForeignKey("Stall_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Stall");
                });

            modelBuilder.Entity("PUP_Online_Lagoon_System.Models.Orders.OrderDetails", b =>
                {
                    b.HasOne("PUP_Online_Lagoon_System.Models.Stall.FoodItem", "Food")
                        .WithMany()
                        .HasForeignKey("Food_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PUP_Online_Lagoon_System.Models.Orders.ItemOrder", "Order")
                        .WithMany()
                        .HasForeignKey("Order_ID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Food");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PUP_Online_Lagoon_System.Models.Stall.FoodItem", b =>
                {
                    b.HasOne("PUP_Online_Lagoon_System.Models.Stall.FoodStall", "Stall")
                        .WithMany()
                        .HasForeignKey("Stall_ID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Stall");
                });

            modelBuilder.Entity("PUP_Online_Lagoon_System.Models.Stall.FoodStall", b =>
                {
                    b.HasOne("PUP_Online_Lagoon_System.Models.Account.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("Vendor_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Vendor");
                });
#pragma warning restore 612, 618
        }
    }
}
