// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PUP_Online_Lagoon_System.Models;

#nullable disable

namespace PUP_Online_Lagoon_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PUP_Online_Lagoon_System.Models.Account.Customer", b =>
                {
                    b.Property<string>("Customer_ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("User_ID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Customer_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("PUP_Online_Lagoon_System.Models.Account.User", b =>
                {
                    b.Property<string>("User_ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("User_ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PUP_Online_Lagoon_System.Models.Account.Customer", b =>
                {
                    b.HasOne("PUP_Online_Lagoon_System.Models.Account.User", "User")
                        .WithMany()
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
